# This is a sample build configuration for C++ – Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: vcatechnology/ubuntu-toolchain
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - make -DFORCE_NO_OPENMP=TRUE -DFORCE_NO_PYTHON -DFORCE_NO_HDF5 all
          - make -DFORCE_NO_OPENMP=TRUE -DFORCE_NO_PYTHON -DFORCE_NO_HDF5 test

